name: flutter_facebook_auth_platform_interface
description: A common platform interface for the flutter_facebook_auth plugin.
version: 6.1.2
homepage: https://github.com/darwin-morocho/flutter-facebook-auth/tree/master/facebook_auth_platform_interface
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4


